name: Development

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # - name: Build
      #   run: |
      #     docker-compose build

      # - name: Test
      #   run: |
      #     docker-compose run backend npm test

      - name: Install sshpass
        run: |
          sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy
        run: |
          sshpass -p "${{ secrets.DEV_SERVER_PASSWORD }}" \
          ssh -o StrictHostKeyChecking=no \
          ${{ secrets.DEV_SERVER_USERNAME }}@${{ secrets.DEV_SERVER_HOST }} \
          'cd ~/apps/naruto && \
          git pull origin development && \
          git checkout development && \

          export POSTGRES_USER=${{ secrets.DEV_POSTGRES_USER }} && \
          export POSTGRES_PASSWORD=${{ secrets.DEV_POSTGRES_PASSWORD }} && \
          export POSTGRES_DB=${{ secrets.DEV_POSTGRES_DB }} && \
          export POSTGRES_HOST=${{ secrets.DEV_POSTGRES_HOST }} && \
          export POSTGRES_PORT=${{ secrets.DEV_POSTGRES_PORT }} && \
          export VITE_BACKEND_URL=${{ secrets.DEV_VITE_BACKEND_URL }} && \

          docker-compose down && \
          docker-compose up -d'

      - name: Test
        run: |
          docker-compose run backend npm test