name: Development

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install sshpass
        run: |
          sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy
        run: |
          sshpass -p "${{ secrets.DEV_SERVER_PASSWORD }}" \
          ssh -o StrictHostKeyChecking=no \
          ${{ secrets.DEV_SERVER_USERNAME }}@${{ secrets.DEV_SERVER_HOST }} \
          'cd ~/apps/naruto && \
          git pull origin development && \
          git checkout development && \
          
          rm .env
          echo "POSTGRES_USER=${{ secrets.DEV_POSTGRES_USER }}" >> .env && \
          echo "POSTGRES_PASSWORD=${{ secrets.DEV_POSTGRES_PASSWORD }}" >> .env && \
          echo "POSTGRES_DB=${{ secrets.DEV_POSTGRES_DB }}" >> .env && \
          echo "POSTGRES_HOST=${{ secrets.DEV_POSTGRES_HOST }}" >> .env && \
          echo "POSTGRES_PORT=${{ secrets.DEV_POSTGRES_PORT }}" >> .env && \
          echo "VITE_BACKEND_URL=${{ secrets.DEV_VITE_BACKEND_URL }}" >> .env && \

          docker-compose down && \
          docker-compose up -d --build'

      - name: Test
        run: |
          docker-compose run backend npx jest